from pydantic import BaseModel
from typing import Generic, Optional, TypeVar


class OcrBankStatementLine(BaseModel):
    """This file is automatically generated, please do not modify"""

    """ 交易日期 """
    date: str = None
    """ 交易金额 """
    amount: str = None
    """ 交易类型 """
    transactionType: Optional[str] = None
    """ 交易备注 """
    description: str = None
    """ 交易余额 """
    balance: Optional[str] = None
